### ISSUE TITLE
undefined symbol on node 10.7

### ISSUE THREAD

**Issue by hlolli** [nwhetsell/csound-api#15]
This is the error message I'm getting
```
> require("csound-api")
Error: /home/hlolli/Music/erkitid_2018/node_modules/csound-api/build/Release/csound-api.node: undefined symbol: _ZN2v814ObjectTemplate11SetAccessorENS_5LocalINS_4NameEEEPFvS3_RKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS3_NS1_IS5_EERKNS4_IvEEESB_NS_13AccessControlENS_17PropertyAttributeENS1_INS_17AccessorSignatureEEENS_14SideEffectTypeE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

I'm on NixOs whith node version 10.7.0, boost 1.66.0 and csound 6.11.0.

This could be nixOs related issue. Maybe I try this with node10 on other OS/distro to confirm.

**Comment by nwhetsell** [comment]
Weird; I just triggered a [new build on Travis](https://travis-ci.org/nwhetsell/csound-api/builds/424526353) and everything seems to be fine with Node.js 10.9.0.

**Comment by hlolli** [comment]
Yes, false alarm. I started recognizing a pattern when more nan based node modules were also failing.

I had completly forgotten about npm config for nodedir when I was manually compiling node and had to tell node-gyp where to find the header files.

`npm config delete nodedir` fixed it for me.

Sorry for the noise :Þ
