### ISSUE TITLE
Possibility of supressing stdout/stderr writes?

### ISSUE THREAD

**Issue by hlolli** [nwhetsell/csound-api#16]
I'm playing around with some nodejs cli tool hacking. I'm looking to create csound instances for specific tasks like `csound.NewOpcodeList`, but on each create I get the initial csound logs

```
0dBFS level = 32768.0
--Csound version 6.11 (double samples) Jan  1 1970
[commit: none]
libsndfile-1.0.28
```

But `csound.SetMessageCallback` can only take effect after csound instance is created. This is certainly csound related. But maybe in the nan bindings, there could be a env variable or global variable, or function that doesn't take csound instance as parameter, that could signal, not to print these messages?

I've tried supressing this by tapping into the process.stdout.write, but this is probably on another thread so little I can do. I could execute this in a thread worker, but that's still experimental technology.

**Comment by nwhetsell** [comment]
You can do this with [`csound.SetDefaultMessageCallback`](https://github.com/nwhetsell/csound-api#SetDefaultMessageCallback), I believe:

```javascript
csound.SetDefaultMessageCallback(() => {});
```

I use this to simplify the output of csound-api’s tests:

https://github.com/nwhetsell/csound-api/blob/f520360e2f1ff98e3453a1ced8f4637e37d8cb8e/spec/csound-api-spec.js#L171

**Comment by hlolli** [comment]
Bingo! Didn't know about that one.

Thanks :)
