### ISSUE TITLE
error with boost when installing csound-api

### ISSUE THREAD

**Issue by zappfinger** [nwhetsell/csound-api#3]
I'm on a Raspberry Pi 3 (Wheezy) and following your steps. (Except I do not execute the command to install csound, since that I have that already.) I do execute the `ln` command, though.

After that, when I do:

```
npm install csound-api
```

I get the following error:

```
> csound-api@0.9.4 install /home/pi/node_modules/csound-api
> node-gyp rebuild

make: Entering directory '/home/pi/node_modules/csound-api/build'
  CXX(target) Release/obj.target/csound-api/src/csound-api.o
../src/csound-api.cc:1:36: fatal error: boost/lockfree/queue.hpp: No such file or directory
 #include <boost/lockfree/queue.hpp>
```

It seems a problem with boost?

When I install boost again, it says it is already the latest version..

**Comment by nwhetsell** [comment]
Can you open a Terminal and enter

``` sh
g++ -E -x c++ - -v < /dev/null
```

This should show the directories that GCC searches for headers. In the output of that, you should see this line:

```
#include <...> search starts here:
```

Somewhere below that, you should see this line:

```
End of search list.
```

Is the directory containing Boost somewhere between those two lines? For example, if your boost directory is in /usr/local/include, is `/usr/local/include` between those two lines?

**Comment by zappfinger** [comment]
I think I know what the problem is:

the lockfree library was introduced in boost 1.60. On my Pi apt-get  installed a much older version. I'm compiling boost 1.63 now (takes a long time) and let you know how it  goes.

Richard

**Comment by zappfinger** [comment]
The boost version was the issue. Csound-api installs fine now, only a 
few warnings:

make: Entering directory '/home/pi/node_modules/csound-api/build'
   CXX(target) Release/obj.target/csound-api/src/csound-api.o
../src/csound-api.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE 
SetControlChannelHints(Nan::NAN_METHOD_ARGS_TYPE)':
../src/csound-api.cc:863:34: warning: missing initializer for member 
'controlChannelHints_s::behav' [-Wmissing-field-initializers]
    controlChannelHints_t hints = {};
                                   ^
../src/csound-api.cc:863:34: warning: missing initializer for member 
'controlChannelHints_s::dflt' [-Wmissing-field-initializers]
../src/csound-api.cc:863:34: warning: missing initializer for member 
'controlChannelHints_s::min' [-Wmissing-field-initializers]

etc.
So I guess it will work.
Thanks!

Richard

**Comment by nwhetsell** [comment]
Excellent!

The warnings are nothing to worry about; the `hints` struct will be initialized to all zeros.
