### ISSUE TITLE
Feature request and version error

### ISSUE THREAD

**Issue by hlolli** [nwhetsell/csound-api#6]
Two seperated things, must add that I'm a nodejs noob so these may end up just being questions.

Firstly, as I'm running on a self-hosted cljs-nodejs environment unlike before, I now get this error
```
Error: The module '/home/hlolli/csound/node-panaeolus/node_modules/csound-api/build/Release/csound-api.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
```
I guess I could either recompile this module or version bump the project?

Second thing is again related to the .PerformAsync function. In the spirit of the csound-api examples, it would be great to deliver a function pointer like you already provide as the second parameter to .PerformAsync, which as I see gets called at the end of performance. But also a function pointer that gets called on every control rate (ex. a .PerformKsmps recursion), that way one can do js callback from the csound thread. Maybe there's a more clever way around this, but I can't think of anything better than setting super fast .setInterval to measure how much time has passed in csound.

**Comment by nwhetsell** [comment]
Resolving that error message depends on how you built csound-api. If you installed csound-api by running

```sh
npm install csound-api
```

then it’s possible that your ClojureScript environment is using Node.js 7, but `npm` is working with Node.js 6 ([here](https://nodejs.org/en/download/releases/) is a list of Node.js versions and `NODE_MODULE_VERSION` codes). You may need to upgrade to Node.js 7 or use something like [`nvm`](https://github.com/creationix/nvm), and then reinstall csound-api.

As for getting a JavaScript callback for every control period, one thing I could try is a `PerformKsmpsAsync` function that takes a callback with an argument indicating whether performance is finished or not. Would that work?

**Comment by hlolli** [comment]
Ok not up to date on these Node.js versions, new info for me, so I'll investigate further.

For that proposed function, yes that would work, I think (maybe) it would need two function arguments, one for when the performance has ended, for a graceful quit, and other one that's called every control perioid, so for kr=4410 it would potentially evaluate 4410 console.log per second. That would be very very useful for what I'm using csound for. If an argument would be given to that potential function, then it could be the value of timeinstk (or basically the amount of k cycles since start of performance), but I see that as optional but useful value.

**Comment by hlolli** [comment]
Thanks, couldn't wait to try this function out and printin a string 4410x second doesn't even push my cpu load above 1%. Wow, I'm amazed. I had to install nodev7 manually, then it stopped complaining about version conflict. This code may be the basis of my next live-coding performance next month, so I ow you beers at least.  See you around :+1:

**Comment by nwhetsell** [comment]
Awesome, I hope your performance goes well!

**Comment by hlolli** [comment]
Hi again,

im trying to create a sequencer with the new function, but it tends to miss events alot, probably due to how the inconsistency. Just printing the output, on closer look, the output is typically something like this
```
7134
7140
7140
7145
7150
7150
7156
7156
7161
7161
7166
7166
7172
7177
7177
7182
7182
7188
7193
7193
```
Maybe you can have a guess what's causing the skips and repeats of the same number, the code producing this is simply
```
(.PerformKsmpsAsync
         csound Csound
         (fn [] (println (.GetControlChannel
                                csound Csound "tickcnt" nil)))
         (fn [] (.Stop csound Csound)))
```
I also post the csound instrument for completion
```
nchnls=2\n0dbfs=1\n
  sr=44100\n
  ksmps=32\n
  ;; kr=441\n
  alwayson 1\n
  ;;alwayson 10000\n
  instr 1\n
  zakinit 4, 1 \n
  ktickcnt init 0
  gkmetrofreq chnget \"metro\"
  kmetro metro gkmetrofreq
  if kmetro == 1 then
  chnset ktickcnt, \"tickcnt\"
  ktickcnt += 1
  endif
  endin\n
```

**Comment by nwhetsell** [comment]
You don’t say what output is expected, which makes it difficult to diagnose an issue (assuming there is one).

If you’re trying to synchronize events using `PerformKsmpsAsync` and `GetControlChannel`, my guess is you’ll have difficulty, because that’s not what those functions are for. The `controlPeriodFunction` you pass to [`PerformKsmpsAsync`](https://github.com/nwhetsell/csound-api#PerformKsmpsAsync) is _queued_ to run after Csound runs a control period on another thread. The implementation of [`Nan::AsyncProgressWorker`](https://github.com/nodejs/nan/blob/master/doc/asyncworker.md#nanasyncprogressworkerbase--nanasyncprogressworker) determines when the `controlPeriodFunction` actually runs, and this may be well after a control period ends. [`GetControlChannel`](https://github.com/nwhetsell/csound-api#GetControlChannel) is intended for updating controls in a user interface.

I’m afraid your Csound instrument, as pasted, contains syntax errors. For example, the two `\n` sequences in the first line are not valid Csound syntax. I’m guessing it should look more like

```csound
nchnls=2
0dbfs=1
sr=44100
ksmps=32
;; kr=441
alwayson 1
;;alwayson 10000
instr 1
  zakinit 4, 1
  ktickcnt init 0
  gkmetrofreq chnget "metro"
  kmetro metro gkmetrofreq
  if kmetro == 1 then
    chnset ktickcnt, "tickcnt"
    ktickcnt += 1
  endif
endin
```

**Comment by hlolli** [comment]
Ok, this was bit ill thought on my side. Not only do I have to account for
the differencies of the kontrol-rate vs the frequency of the metro, but
also for the async callback nature of node-async. But just using a counter
in nodejs-world instead of csound world, no synchronization is needed and
no event is lost. I may have to relook into this if I need to sync my metro
to someone else's metro, but that is an eternal source of problem.

here's an excerpt of ouput just incrementing in nodejs,
```
7865
7866
7867
7868
7869
7870
7871
7872
7873
7874
7875
7876
7877
7878
7879
7880
7881
7882
7883
7884
7885
7886
7887
7888
7889
7890
```

Hope Im good now, thanks!

2017-02-24 2:26 GMT+01:00 Nate Whetsell <notifications@github.com>:
